image: docker:20.10.16

services:
  - docker:20.10.16-dind

stages:
  - test
  - deploy
  - android-release

variables:
  PACKAGE_NAME: "ru.mafbase.app"
  SECURE_FILES_DOWNLOAD_PATH: './secure-files/'

build_android_app:
  stage: android-release
  needs:
    - test
    - code_quality
  image: "instrumentisto/flutter:3.38.3-androidsdk36-r0"
  when: manual
  tags:
    - docker
  before_script:
    - apt-get update
    - apt-get install curl -y
    # Устанавливаем утилиту для загрузки Secure Files
    - curl --silent "https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer" | bash
    - echo "Downloading Secure Files..."
    - mkdir -p $SECURE_FILES_DOWNLOAD_PATH
    - download-secure-files $SECURE_FILES_DOWNLOAD_PATH
    - echo "Moving Keystore..."
    - cp $SECURE_FILES_DOWNLOAD_PATH/mafbase.jks $CI_PROJECT_DIR/android/mafbase.jks
    - echo "Creating key.properties file..."
    - echo "storePassword=$KEYSTORE_PASSWORD" > android/key.properties
    - echo "keyPassword=$KEY_PASSWORD" >> android/key.properties
    - echo "keyAlias=$KEY_ALIAS" >> android/key.properties
    - echo "storeFile=$CI_PROJECT_DIR/android/mafbase.jks" >> android/key.properties
  script:
    - echo "Building the app..."
    - flutter build appbundle --release
  artifacts:
    paths:
      - build/app/outputs/bundle/release/app-release.aab
    expire_in: 1 hour
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

publish_to_rustore:
  stage: android-release
  image: python:3.9-slim
  tags:
    - docker
  before_script:
    - apt-get update
    - apt-get install -y curl
    - echo "Extracting build number..."
    - export BUILD_NUMBER=$(grep -E '^version:' pubspec.yaml | awk -F '+' '{print $2}')
    - echo "Build number - $BUILD_NUMBER"
    - echo "Installing Python dependencies..."
    - pip3 install pycryptodome tqdm requests requests-toolbelt
  script:
    - echo "Uploading app to RuStore..."
    - python3 rustore-api-key-gen.py "$RUSTORE_KEY_ID" "$RUSTORE_PRIVATE_KEY" "$PACKAGE_NAME" build/app/outputs/bundle/release/app-release.aab
  needs:
    - build_android_app
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  allow_failure: false

build_job:
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  tags:
    - docker
  script:
    - docker build --no-cache --build-arg "REGISTRY_HOST=$REGISTRY_HOST" -t "$REGISTRY_HOST/seating-generator-flutter:latest" .
    - docker push "$REGISTRY_HOST/seating-generator-flutter:latest"

sentry-upload:
  image: "instrumentisto/flutter:3.38.3-androidsdk36-r0"
  needs:
    - build_job
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  tags:
    - docker
  stage: deploy
  script:
    - flutter build web --source-maps
    - flutter packages pub run sentry_dart_plugin


code_quality:
  stage: test
  tags:
    - docker
  image: "instrumentisto/flutter:3.38.3-androidsdk36-r0"
  before_script:
    - flutter pub global activate dart_code_metrics
    - export PATH="$PATH:$HOME/.pub-cache/bin"
  script:
    - metrics lib -r codeclimate  > gl-code-quality-report.json
  artifacts:
    reports:
      codequality: gl-code-quality-report.json

test:
  stage: test
  tags:
    - docker
  image: "instrumentisto/flutter:3.38.3-androidsdk36-r0"
  before_script:
    - apt-get update
    - apt-get install -y lcov
    - flutter pub global activate junitreport
    - export PATH="$PATH:$HOME/.pub-cache/bin"
  script:
    - flutter test --machine --coverage | tojunit -o report.xml
    - lcov --summary coverage/lcov.info
    - genhtml coverage/lcov.info --output=coverage
  coverage: '/lines\.*: \d+\.\d+\%/'
  artifacts:
    name: coverage
    paths:
      - $CI_PROJECT_DIR/coverage
    reports:
      junit: report.xml

deploy:
  stage: deploy
  image: "$REGISTRY_HOST/deployer:1.0.0"
  tags:
    - docker
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  needs:
    - build_job
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_KEY"
    - ssh-add <(echo "$SSH_KEY")
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -p 22 "$DEPLOY_HOST" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - ssh "$DEPLOY_USER"@"$DEPLOY_HOST" "./restart.sh"
  environment: production

