image: docker:20.10.16

services:
  - docker:20.10.16-dind

stages:
  - test
  - deploy
  - android-release
variables:
  PACKAGE_NAME: "ru.mafbase.app"


build_android_app:
  stage: android-release
  image: "$REGISTRY_HOST/flutter-builder:3.19.3"
  when: manual
  script:
    - flutter build appbundle --release
  artifacts:
    paths:
      - build/app/outputs/bundle/release/app-release.aab
    expire_in: 1 hour
  only:
    - main

publish_to_rustore:
  stage: android-release
  before_script:
    - echo "Extracting app version..."
    - export VERSION_ID=$(grep -E '^version:' pubspec.yaml | awk '{print $2}' | cut -d'+' -f1)
    - echo "App version - $VERSION_ID"
  script:
    - echo "Uploading app to RuStore..."
    - |
      curl -X POST "https://public-api.rustore.ru/public/v1/application/${PACKAGE_NAME}/version/${VERSION_ID}/aab" \
        -H "Public-Token: $RU_STORE_API_KEY" \
        -F "file=@build/app/outputs/bundle/release/app-release.aab"
  dependencies:
    - build_android_app
  only:
    - main
  when: manual
  allow_failure: false

build_job:
  stage: deploy
  tags:
    - docker
  script:
    - docker build --no-cache --build-arg "REGISTRY_HOST=$REGISTRY_HOST" -t "$REGISTRY_HOST/seating-generator-flutter:latest" .
    - docker push "$REGISTRY_HOST/seating-generator-flutter:latest"

code_quality:
  stage: test
  tags:
    - docker
  image: "$REGISTRY_HOST/flutter-builder:3.19.3"
  before_script:
    - flutter pub global activate dart_code_metrics
    - export PATH="$PATH:$HOME/.pub-cache/bin"
  script:
    - metrics lib -r codeclimate  > gl-code-quality-report.json
  artifacts:
    reports:
      codequality: gl-code-quality-report.json

test:
  stage: test
  tags:
    - docker
  image: "$REGISTRY_HOST/flutter-builder:3.19.3"
  before_script:
    - apt-get update
    - apt-get install -y lcov
    - flutter pub global activate junitreport
    - export PATH="$PATH:$HOME/.pub-cache/bin"
  script:
    - flutter test --machine --coverage | tojunit -o report.xml
    - lcov --summary coverage/lcov.info
    - genhtml coverage/lcov.info --output=coverage
  coverage: '/lines\.*: \d+\.\d+\%/'
  artifacts:
    name: coverage
    paths:
      - $CI_PROJECT_DIR/coverage
    reports:
      junit: report.xml

deploy:
  stage: deploy
  image: "$REGISTRY_HOST/deployer:1.0.0"
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  tags:
    - docker
  needs:
    - build_job
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_KEY"
    - ssh-add <(echo "$SSH_KEY")
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -p 22 "$DEPLOY_HOST" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - ssh "$DEPLOY_USER"@"$DEPLOY_HOST" "./restart.sh"
  environment: production
