build:
  stage: build
  tags:
    - flutter
  script:
    - flutter build web --release
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build

test:
  stage: test
  tags:
    - flutter
  script:
    - flutter analyze
    - flutter pub global activate junitreport
    - export PATH="$PATH:$HOME/.pub-cache/bin"
    - flutter test --machine --coverage | tojunit -o report.xml
    - lcov --summary coverage/lcov.info
    - genhtml coverage/lcov.info --output=coverage
  coverage: '/lines\.*: \d+\.\d+\%/'
  artifacts:
    name: coverage
    paths:
      - $CI_PROJECT_DIR/coverage
    reports:
      junit: report.xml
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build

deploy:
  stage: deploy
  tags:
    - flutter
  script:
    - cd build
    - zip client.zip web/ -r
    - scp -i ~/.ssh/id_rsa -P 2323 client.zip server-runner@mafia-generator.tomsk.ru:~/
    - ssh -i ~/.ssh/id_rsa server-runner@mafia-generator.tomsk.ru -p 2323 "./update_client.sh"
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build

