// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyWF5a46EGR6STNdNnhCPZuFcY0KSexSo',
    appId: '1:778845684766:web:1142d64f6781a63ac15a0f',
    messagingSenderId: '778845684766',
    projectId: 'mafbase-f35dd',
    authDomain: 'mafbase-f35dd.firebaseapp.com',
    storageBucket: 'mafbase-f35dd.firebasestorage.app',
    measurementId: 'G-HDEQJK95Z0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_J5zwuMIZUf6q4pXy7-6jhew5Sc5h3UI',
    appId: '1:778845684766:android:781a637199ea8715c15a0f',
    messagingSenderId: '778845684766',
    projectId: 'mafbase-f35dd',
    storageBucket: 'mafbase-f35dd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbyRx1WYfu3V-JgMnmXB8PDM9GVeWUYZ0',
    appId: '1:778845684766:ios:6af919ab575a58acc15a0f',
    messagingSenderId: '778845684766',
    projectId: 'mafbase-f35dd',
    storageBucket: 'mafbase-f35dd.firebasestorage.app',
    iosBundleId: 'ru.mafbase.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbyRx1WYfu3V-JgMnmXB8PDM9GVeWUYZ0',
    appId: '1:778845684766:ios:fccc0dda908c6f85c15a0f',
    messagingSenderId: '778845684766',
    projectId: 'mafbase-f35dd',
    storageBucket: 'mafbase-f35dd.firebasestorage.app',
    iosBundleId: 'com.example.seatingGeneratorWeb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyWF5a46EGR6STNdNnhCPZuFcY0KSexSo',
    appId: '1:778845684766:web:cc1a4f41de603bddc15a0f',
    messagingSenderId: '778845684766',
    projectId: 'mafbase-f35dd',
    authDomain: 'mafbase-f35dd.firebaseapp.com',
    storageBucket: 'mafbase-f35dd.firebasestorage.app',
    measurementId: 'G-4DS2KJPVD4',
  );
}
