// Mocks generated by Mockito 5.4.2 from annotations
// in seating_generator_web/test/repositories/cannot_meet_tournament_repository_mock.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:seating_generator_web/domain/models/player_model.dart' as _i4;
import 'package:seating_generator_web/domain/repositories/cannot_meet_tournament_repository.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [CannotMeetTournamentRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCannotMeetTournamentRepository extends _i1.Mock
    implements _i2.CannotMeetTournamentRepository {
  @override
  _i3.Future<List<List<_i4.PlayerModel>>> pairs(int? tournamentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #pairs,
          [tournamentId],
        ),
        returnValue: _i3.Future<List<List<_i4.PlayerModel>>>.value(
            <List<_i4.PlayerModel>>[]),
        returnValueForMissingStub:
            _i3.Future<List<List<_i4.PlayerModel>>>.value(
                <List<_i4.PlayerModel>>[]),
      ) as _i3.Future<List<List<_i4.PlayerModel>>>);
  @override
  _i3.Future<dynamic> insertPair(
    int? tournamentId,
    _i4.PlayerModel? first,
    _i4.PlayerModel? second,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertPair,
          [
            tournamentId,
            first,
            second,
          ],
        ),
        returnValue: _i3.Future<dynamic>.value(),
        returnValueForMissingStub: _i3.Future<dynamic>.value(),
      ) as _i3.Future<dynamic>);
  @override
  _i3.Future<dynamic> deletePair(
    int? tournamentId,
    _i4.PlayerModel? first,
    _i4.PlayerModel? second,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deletePair,
          [
            tournamentId,
            first,
            second,
          ],
        ),
        returnValue: _i3.Future<dynamic>.value(),
        returnValueForMissingStub: _i3.Future<dynamic>.value(),
      ) as _i3.Future<dynamic>);
}
